service: campus-exchange-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  environment:
    SUPABASE_URL: https://qhfqffutgejqlbkbkfmp.supabase.co
    SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoZnFmZnV0Z2VqcWxia2JrZm1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczMTMzODMsImV4cCI6MjA5Mjg4OTM4M30.U3uYUWrhwcKx9tuzyAVBXUPa80jSoUVOQiA622Guks4

functions:
  getListings:
    handler: handlers/listings.getAll
    events:
      - http:
          path: listings
          method: get
          cors: true

  getListingById:
    handler: handlers/listings.getById
    events:
      - http:
          path: listings/{id}
          method: get
          cors: true

  createListing:
    handler: handlers/listings.create
    events:
      - http:
          path: listings
          method: post
          cors: true
